### ISSUE TITLE
altaz_to_radec fails when coordinates are given as quantities

### ISSUE THREAD

**Issue by danjampro** [panoptes/panoptes-utils#248]
`utils.altaz_to_radec` as a hardcoded multiplication by `u.degree` which causes it to fail if the `alt` or `az` are provided as quantity values.  Suggest using `get_quantity_value`. 

Line: https://github.com/panoptes/panoptes-utils/blob/bccd8f963b92b26ad90e30b1a52207b8399aa290/src/panoptes/utils/utils.py#L212

**Comment by AnthonyHorton** [comment]
I'd call `get_quantity_value()` deprecated at this point, because astropy now has a similar function built in, the `to_value()` method of the `Quantity` class.

**Comment by wtgee** [comment]
> I'd call `get_quantity_value()` deprecated at this point, because astropy now has a similar function built in, the `to_value()` method of the `Quantity` class.

But out `get_quantity_value` will return the same value if it is *not* a quantity, which astropy won't do.  There are a few cases where we pass in a value and (for some reason) can't guarantee that it's a quantity going in. 

But it is a very thin wrapper. This is all of `get_quantity_value`:

https://github.com/panoptes/panoptes-utils/blob/bccd8f963b92b26ad90e30b1a52207b8399aa290/src/panoptes/utils/utils.py#L293-L296
